title: Emre Ozkan
description: Software Developer
baseurl: ""
url: https://github.com/SamoTheFiend
homepage: Home Page

theme: minimal

# site settings
taglong: Software Developer
tagshort: Software Developer

# author settings
author:
  name: Emre Ozkan
  email: emrefuatozkan@gmail.com
photo: assets/files/photo.jpg
address: San Diego, CA
#phone: +1 858 858 8585

# social media links
social:
  #facebook: username
  github: SamoTheFiend
  #instagram: username
  linkedin: emre-ozkan-753061170
  stackoverflow: 23460163/samo
  x: SamoTheFiend

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
